# Generated by Django 2.1.7 on 2021-05-31 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210531_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 5, 31, 17, 13, 2, 422984)),
        ),
    ]
